name: decorated_google_maps_flutter
description: A Flutter plugin for integrating Google Maps decorated with widgets such as charts or custom displays in iOS and Android applications.
homepage: https://github.com/mehmetoguzderin/decorated_google_maps_flutter
version: 0.1.0

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^1.0.0
  google_maps_flutter: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # TODO(iskakaushik): The following dependencies can be removed once
  # https://github.com/dart-lang/pub/issues/2101 is resolved.
  flutter_driver:
    sdk: flutter
  test: ^1.6.0
  pedantic: ^1.8.0

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
